---
# file: roles/actual_budget/tasks/main.yaml

- name: Ensure directory
  ansible.builtin.file:
    path: '{{ actual_directory }}'
    state: '{{ (actual_install_status == "present") | ternary("directory", "absent") }}'

- name: Generate self-signed certificate
  include_role:
    name: self-signed-cert
  vars:
    dest_directory: "{{ actual_directory }}/{{ actual_data_directory }}"
  tags:
    - certificate
    - self-signed

- name: Copy Docker Compose to root directory
  ansible.builtin.template:
    src: "{{ item }}"
    dest: '{{ actual_directory }}/{{ item | replace(".j2", "")}}'
  loop:
    - docker-compose.yaml.j2

- name: Copy certificate config to data directory
  ansible.builtin.template:
    src: "{{ item }}"
    dest: '{{ actual_directory }}/{{ actual_data_directory }}/{{ item | replace(".j2", "")}}'
  loop:
    - config.json.j2
  tags: 
    - certificate
    - self-signed

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ actual_directory }}"
    pull: always
    state: '{{ actual_install_status }}'
    recreate: auto
  register: output

- name: Configure Actual Firewall rules
  include_role:
    name: ufw_config
  tags:
    - firewall
    - ufw

- name: Backup | Actual DB
  ansible.builtin.cron:
    name: Copy tarball of actual budget
    minute: "30"
    hour: "7" # UTC time for 0200
    month: "*"
    weekday: Sun
    job: sudo tar -czvf {{ backups_destination }}/actual_budget.tar {{ actual_directory }}/{{ data_directory_name }}/
    state: '{{ actual_install_status }}'
  when: backups_destination is defined
