---
# roles/qbittorrent/vars/main.yml
qbittorrent_nox_package_state: present
qbittorrent_nox_webui_port: 8080
daemon_path: /etc/systemd/system/
daemon_config: qBittorrent-nox.service

conf_lines: 
  - line: 'Session\AddExtensionToIncompleteFiles'
    value: 'Session\AddExtensionToIncompleteFiles={{ config_add_ext_to_incomplete_files }}'
  - line: 'Session\DefaultSavePath'
    value: 'Session\DefaultSavePath={{ config_default_save_path }}'
    after: "[BitTorrent]"
  - line: 'Session\TorrentExportDirector'
    value: 'Session\TorrentExportDirector={{ config_torrentfile_work_path }}'
    after: "[BitTorrent]"
  - line: 'Session\TorrentExportDirectory'
    value: 'Session\TorrentExportDirectory={{ config_torrentfile_complete_path }}'
    after: "[BitTorrent]"
  - line: 'Session\TempPathEnabled'
    value: 'Session\TempPathEnabled={{ config_default_save_path is defined | ternary("true", "false") }}'
    after: "[BitTorrent]"
  - line: 'Session\TempPath'
    value: 'Session\TempPath={{ config_staging_path }}'
    after: "[BitTorrent]"
  - line: 'Session\Interface'
    value: 'Session\Interface={{ config_preferred_interface }}'
    after: "[BitTorrent]"
  - line: 'Session\InterfaceName'
    value: 'Session\InterfaceName={{ config_preferred_interface }}'
    after: "[BitTorrent]"
  - line: 'DynDNS\DomainName'
    value: 'DynDNS\DomainName={{ config_dyndns_domain_name }}'
    after: "[Preferences]"
  - line: 'DynDNS\Enabled'
    value: 'DynDNS\Enabled=false'
    after: "[Preferences]"
  - line: 'DynDNS\Password'
    value: 'DynDNS\Password='
    after: "[Preferences]"
  - line: 'DDynDNS\Service'
    value: 'DynDNS\Service=NoIP'
    after: "[Preferences]"
  - line: 'DynDNS\Username'
    value: 'DynDNS\Username={{ config_dyndns_user_name }}'
    after: "[Preferences]"
  - line: 'WebUI\AuthSubnetWhitelist'
    value: 'WebUI\AuthSubnetWhitelist={{ whitelist_subnet }}'
    after: "[Preferences]"
  - line: 'WebUI\AuthSubnetWhitelistEnabled'
    value: 'WebUI\AuthSubnetWhitelistEnabled={{ config_webui_login_from_whitelist_subnet }}'
    after: "[Preferences]"
  - line: 'WebUI\Port'
    value: 'WebUI\Port={{ qbittorrent_nox_webui_port }}'
    after: "[Preferences]"
  - line: 'WebUI\Username'
    value: 'WebUI\Username={{ config_qbittorrent_webui_username }}'
    after: "[Preferences]"
  - line: 'WebUI\Password_PBKDF2'
    value: 'WebUI\Password_PBKDF2={{ qbitorrent_webui_password }}' # vaulted
    after: "[Preferences]"
qbitorrent_firewall_rules:
  - rule: allow
    proto: 'tcp'
    port: "{{ qbittorrent_nox_webui_port }}"
    to_ip: "{{ hostvars['microserver'].ansible_host }}"
    from_ip: "{{ local_subnet_range }}"
    comment: Allow local network Qbittorrent WebUI access