---
- name: Copy a new "smb.conf" file into place, backing up the original if it differs from the copied version
  ansible.builtin.copy:
    src: files/smb.conf
    dest: "{{ config_path }}"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - restart service

- name: Create samba user
  shell: >
    (pdbedit --user={{ item.username }} 2>&1 > /dev/null)
    || (echo '{{ item.password }}'; echo '{{ item.password }}')
    | smbpasswd -s -a {{ item.username }}
  register: smbpasswd
  changed_when: "'Added user' in smbpasswd.stdout"
  with_items: "{{ samba_users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Ubuntu | Firewall | Samba Firewall config
  include_role:
    name: ufw_config
  vars:
    ruleset: "{{ smb_firewall_rules }}"