---

# ansible-playbook run_subtask.yaml -i inventory_prod.ini --vault-password-file=.vault_pwd_file

- name: Playbook testing
  hosts: microserver
  become: true

  vars: 
    local_subnet_range: 192.168.0.0/24

  vars_files:
    - vars/required_software.yaml
    - vars/manual_software.yaml
    - vars/storage_pool.yaml
    - vars/ubuntu_groups.yaml
    - vars/users.yaml
    - vars/service_accounts.yaml
    - vars/cron_jobs.yaml
    - vars/monitoring.yaml
    - vars/credentials.yaml
    - vars/actual_budget.yaml


  tasks:
    - name: Ubuntu | Run a single substask file    
      ansible.builtin.import_tasks:
        file: subtasks/install_actual_budget.yml

      
      # vars:
      #   backup_dst_dir: /micropool/Simon/Backups