---
#roles/configure_onedrive/tasks/main.yml
  - name: Ubuntu | Filesystem | Create required user directories
    ansible.builtin.file:
      state: directory
      path: /home/{{ owner }}/{{ item }}
      owner: "{{ owner }}"
      group: "{{ owner }}"
      mode: 0700
      recurse: yes
    loop:
    - .config/onedrive

  - name: Debug
    debug:
      msg: /home/{{ owner }}/onedrive.ini

  - name: Ubuntu | Onedrive | Copy Configuration templates
    ansible.builtin.template:
      src: files/{{ item }}
      dest: /home/{{ owner }}/.config/onedrive/{{ item | replace(".j2", "")}}
      owner: "{{ owner }}"
      group: "{{ owner }}"
      mode: '0644'
    loop: 
      - config.j2
      - sync_list.j2
    register: configuration_files
    notify: restart service

  # - debug:
  #     var: configuration_files

  #- name: Ubuntu | Onedrive | Run resync if config changed
  #  ansible.builtin.shell: onedrive --synchronize --resync
  #  when: configFile.changed == True or syncFile.changed == True
  #  become: true
  #  become_user: "{{ owner }}"

  - name: Enable service
    ansible.builtin.service:
      name: onedrive@{{ owner }}.service
      enabled: true
      state: started