- name: Move scripts to server
  ansible.builtin.copy:
    src: files/scripts/
    dest: scripts/
    owner: ansible
    group: ansible
    mode: '0740'

- name: Creates an cron job entry"
  ansible.builtin.cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    job: "{{ item.script_path }}"
    state: "{{ item.state | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
  loop:
    "{{ cron_jobs }}"