# microserver/subtasks/create_users.yml 

- name: Linux | Groups | Create all required user groups
  ansible.builtin.group:
    name: "{{ item }}"
  loop: "{{ users | map(attribute='groups') | flatten }}"
  register:
    created_users

- name: Linux | Users | Create all required users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default('Created by ansible')}}"
    groups: "{{ item.groups }}"
    append: true
    shell: "{{ item.shell | default('/bin/bash') }}"
  loop: "{{ users }}"
  register:
    created_users