# microserver/subtasks/create_users.yml 

- name: Linux | Users | Create all required users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default('Created by ansible')}}"
    groups: "{{ item.groups }}"
    append: true
    shell: "{{ item.shell | default('/bin/bash') }}"
  loop: "{{ users }}"
  register:
    created_users