---
#roles/qbittorrent/tasks/main.yml
- debug:
    var:
      svc_accounts

- name: Ensure package is installed.
  ansible.builtin.package:
    name: qbittorrent-nox
    state: "{{ qbittorrent_nox_package_state | default(present) }}"
  notify: restart service

- name: Gather package facts.
  ansible.builtin.package_facts:
    manager: auto

- name: Ensure config directory exists.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ qbittorrent_nox_user }}"
    group: "{{ qbittorrent_nox_user }}"
  with_items:
    - /home/{{ qbittorrent_nox_user }}/.config/
    - /home/{{ qbittorrent_nox_user }}/.config/qBittorrent/

- name: Ensure legal notice is accepted.
  ansible.builtin.lineinfile:
    path: /home/{{ qbittorrent_nox_user }}/.config/qBittorrent/qBittorrent.conf
    regexp: "{{ item.re }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.after | default(omit) }}"
    create: yes
    owner: "{{ qbittorrent_nox_user }}"
    group: "{{ qbittorrent_nox_user }}"
    mode: 0644
  with_items:
    - { re: '^\[LegalNotice\]$', line: "[LegalNotice]" }
    - { re: "^Accepted=true$", line: "Accepted=true", after: '^\[LegalNotice\]$' }

- name: Ensure systemd unit file is present.
  ansible.builtin.template:
    src: qbittorrent-nox.service
    dest: /etc/systemd/system/qbittorrent-nox.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart service
  when: "ansible_service_mgr == 'systemd'"

- name: Linux | qbittorrent-nox | set configuration file content
  ansible.builtin.lineinfile:
    path: /home/{{ qbittorrent_nox_user }}/.config/qBittorrent/qBittorrent.conf
    search_string: "{{ item.line }}"
    line: "{{ item.value }}"
    owner: "{{ qbittorrent_nox_user }}"
    group: "{{ qbittorrent_nox_user }}"
    mode: '0644'
  loop: "{{ conf_lines }}"
  notify:
    - restart service

- name: Ensure service is enabled at boot.
  ansible.builtin.systemd:
    name: qbittorrent-nox
    enabled: yes
    daemon_reload: yes
  when: "ansible_service_mgr == 'systemd'"

- name: Ubuntu | Firewall | Qbittorrent Firewall config
  include_role:
    name: ufw_config
  vars:
    ruleset: "{{ qbitorrent_firewall_rules }}"