

- name: docker prep
  block:

  # - name: Install docker dependencies
  #   include_role:
  #     name: docker

  - name: Create staging directory
    ansible.builtin.file:
      state: directory
      path: "{{ firefly_staging_directory }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      recurse: yes
      mode: '0755'
    
  - name: Move files to remote directory
    ansible.builtin.template:
      src: "{{ item }}"
      dest: "{{ firefly_staging_directory }}{{ (item | replace('.j2','')| split('/'))[-1] }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0644'
    loop:
      - files/.env.j2
      - files/.db.env.j2
      - files/docker-compose.yml
      - files/importer.env.j2

  - name: "Starting docker service"
    ansible.builtin.service:
      name: "docker"
      state: started
      enabled: yes
  tags: docker

- name: Create and start services
  community.docker.docker_compose:
    project_src: "{{ firefly_staging_directory }}"
    # env_file: 
    #   - "{{ firefly_staging_directory }}.env"
    #   - "{{ firefly_staging_directory }}import.env"
    #   - "{{ firefly_staging_directory }}database.env"
  register: output

# - name: Show results
#   ansible.builtin.debug:
#     var: output