- name: prerequisites
  block:
  - name: Add docker to apt repos
    ansible.builtin.shell:
      cmd: | 
        # Add GPG key
        sudo apt-get update
        sudo apt-get install ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
        # Add the repository to Apt sources:
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Install Docker 
    ansible.builtin.apt:
      name: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
      update_cache: yes 
      state: present

  - name: Install docker python package
    ansible.builtin.pip:
      name: 
        - docker==6.1.3 # Issue with 7.0.0 and ansible community see https://github.com/docker/docker-py/issues/3194
        - docker-compose
  tags: prereqs